Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 187, in create_invoice
    return render(request, 'create_invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 187, in create_invoice
    return render(request, 'create_invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 157, in create_invoice
    return redirect('confirm_invoice_items')
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'confirm_invoice_items' not found. 'confirm_invoice_items' is not a valid view function or pattern name.
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Invoice is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Invoice is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Invoice is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /confirminvoiceitems/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 198, in confirminvoiceitems
    return redirect('create invoice')
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create invoice' not found. 'create invoice' is not a valid view function or pattern name.
"GET /confirminvoiceitems/ HTTP/1.1" 500 145
Internal Server Error: /confirminvoiceitems/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 198, in confirminvoiceitems
    return redirect('create invoice')
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create invoice' not found. 'create invoice' is not a valid view function or pattern name.
"GET /confirminvoiceitems/ HTTP/1.1" 500 145
Internal Server Error: /confirminvoiceitems/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 198, in confirminvoiceitems
    return redirect('create invoice')
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create invoice' not found. 'create invoice' is not a valid view function or pattern name.
"GET /confirminvoiceitems/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Invoice is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Invoice is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 136, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'invoice_form': invoice_form,
        'valid_items': valid_items,
        'insufficient_stock': insufficient_stock_products
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 136, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'invoice_form': invoice_form,
        'valid_items': valid_items,
        'insufficient_stock': insufficient_stock_products
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 136, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'invoice_form': invoice_form,
        'valid_items': valid_items,
        'insufficient_stock': insufficient_stock_products
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 136, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'invoice_form': invoice_form,
        'valid_items': valid_items,
        'insufficient_stock': insufficient_stock_products
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 136, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'invoice_form': invoice_form,
        'valid_items': valid_items,
        'insufficient_stock': insufficient_stock_products
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 136, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'invoice_form': invoice_form,
        'valid_items': valid_items,
        'insufficient_stock': insufficient_stock_products
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 136, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'invoice_form': invoice_form,
        'valid_items': valid_items,
        'insufficient_stock': insufficient_stock_products
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 190, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': Product.objects.all(),
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 190, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': Product.objects.all(),
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 190, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': Product.objects.all(),
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 190, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': Product.objects.all(),
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 143, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
    ...<2 lines>...
        'insufficient_stock': insufficient_stock
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create invoice' not found. 'create invoice' is not a valid view function or pattern name.
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Invoice is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Invoice is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Invoice is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Invoice is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Decimal is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 190, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: createinvoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 190, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: createinvoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 190, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: createinvoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 190, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: createinvoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 190, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: createinvoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Decimal is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Decimal is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Decimal is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 123, in save
    obj = self.create_model_instance(data)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 102, in create_model_instance
    session_data=self.encode(data),
                 ~~~~~~~~~~~^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 124, in encode
    return signing.dumps(
           ~~~~~~~~~~~~~^
        session_dict,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        compress=True,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 150, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, serializer=serializer, compress=compress
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 225, in sign_object
    data = serializer().dumps(obj)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Nanma-Janaseva\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Decimal is not JSON serializable
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 146, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'insufficient_stock_products': insufficient_stock_products,
    ...<2 lines>...
        'products': Product.objects.all(),
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 27: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 146, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'insufficient_stock_products': insufficient_stock_products,
    ...<2 lines>...
        'products': Product.objects.all(),
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 27: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 146, in create_invoice
    return render(request, 'confirm_invoice.html', {
        'insufficient_stock_products': insufficient_stock_products,
    ...<2 lines>...
        'products': Product.objects.all(),
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 27: 'endblock'. Did you forget to register or load this tag?
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 128, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 128, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 128, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 128, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 128, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 128, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 128, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 133, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 133, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 133, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 133, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 133, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 133, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 133, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\New folder\Lickees\venv\Lib\site-packages\psycopg2\__init__.py", line 135, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dpg-cungd21opnds73d6k41g-a.singapore-postgres.render.com" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 179, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\New folder\Lickees\venv\Lib\site-packages\psycopg2\__init__.py", line 135, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dpg-cungd21opnds73d6k41g-a.singapore-postgres.render.com" to address: Name or service not known

"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 133, in create_invoice
    'invoice': invoice,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'invoice' where it is not associated with a value
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 143, in create_invoice
    return render(request, 'create_invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
        'insufficient_stock_products': insufficient_stock_products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 175, in create_invoice
    return render(request, 'create_invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
        'insufficient_stock_products': insufficient_stock_products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 143, in create_invoice
    return render(request, 'create_invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
        'insufficient_stock_products': insufficient_stock_products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 175, in create_invoice
    return render(request, 'create_invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
        'insufficient_stock_products': insufficient_stock_products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 186, in create_invoice
    return render(request, 'create_invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
        'insufficient_stock_products': []  # Pass empty list if no products are out of stock
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 147, in create_invoice
    return redirect('confirm_invoice')
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'confirm_invoice' not found. 'confirm_invoice' is not a valid view function or pattern name.
"POST /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 174, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 174, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 185, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
Internal Server Error: /createinvoice/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app\views.py", line 185, in create_invoice
    return render(request, 'create invoice.html', {
        'invoice_form': invoice_form,
        'products': products,
    })
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_invoice.html
"GET /createinvoice/ HTTP/1.1" 500 145
