Internal Server Error: /location_report2/
Traceback (most recent call last):
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\New folder\Lickees\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\New folder\Lickees\BillingSoftware\app2\views.py", line 739, in location_report2
    if invoice.original_money_got is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Invoice2' object has no attribute 'original_money_got'
"POST /location_report2/ HTTP/1.1" 500 145
